name: Apply Kubernetes manifests

on:
  workflow_call:

jobs:
  apply-k8s:
    name: Apply Kubernetes manifests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Download kubeconfig
        uses: actions/download-artifact@v3
        with:
          name: kubeconfig
          path: kubeconfig.txt

      - name: Setup kubeconfig
        run: |
          mkdir -p $HOME/.kube
          cat kubeconfig.txt | base64 --decode > $HOME/.kube/config

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f .github/workflows/K8S/resources.yaml
