name: Apply Kubernetes manifests

on:
  workflow_call:


jobs:
  apply-k8s:
    name: Apply Kubernetes manifests
    runs-on: ubuntu-latest
    steps:
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f .github/workflows/K8S/resources.yaml