name: Continuous Deployment for Comment Service

on:
  workflow_run:
    workflows: ["Continuous Integration for Comment Service"]
    types:
      - completed

env:
  PROJECT_ID: gke-project-423206
  CLUSTER_NAME: autopilot-cluster-1
  ZONE: us-central1

jobs:
  deploy:
    name: Connect to Cluster GKE
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
      
      - name: Authenticate
        uses: google-github-actions/auth@v2
        with: 
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: Configure gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          install_components: 'gke-gcloud-auth-plugin'

      - name: Set cluster context
        run: |
          mkdir -p $HOME/.kube
          gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} --zone ${{ env.ZONE }} --project ${{ env.PROJECT_ID }}

      - name: Save kubeconfig
        run: |
          cat $HOME/.kube/config | base64 | tr -d '\n' > kubeconfig.txt
        id: kubeconfig

      - name: Upload kubeconfig
        uses: actions/upload-artifact@v3
        with:
          name: kubeconfig
          path: kubeconfig.txt

  apply-k8s:
    needs: deploy
    uses: ./.github/workflows/applyK8S.yaml

  notify:
    needs: apply-k8s
    uses: ./.github/workflows/notifyCD.yaml
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
