name: Continuous Integration for Comment Service

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Comment Service 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file pom.xml
