name: Continuous Integration for Comment Service

on:
  push:
    branches:
      - main

jobs:
  testing:
    name: Testing Comment Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Set up MongoDB URI
        run: echo "SPRING_DATA_MONGODB_URI=mongodb://localhost:27017/comment-service" >> $GITHUB_ENV

      - name: Unit Tests
        run: mvn -B test --file pom.xml

  sonar_scan:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=devops-video-sharing
            -Dsonar.organization=devops-video-sharing
            -Dsonar.host.url=${{ secrets.SONARQUBE_URL }}
            -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}

  build-image:
    needs: sonar_scan
    uses: ./.github/workflows/build-image.yaml
    secrets:
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  scan-image:
    needs: build-image
    uses: ./.github/workflows/scan-image.yaml

  notify:
    needs: scan-image
    uses: ./.github/workflows/notifyCI.yaml
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
