name: Send Slack Notification

on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "${{ github.event.workflow_run.conclusion == 'success' ? 'The Continuous Integration for Comment Service workflow has completed successfully.' : 'The Continuous Integration for Comment Service workflow has failed.' }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
