name: test-Slack-Notification
on: [push]

jobs:
  new_push_job:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification on Slack using Webhooks
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "Hello, World!"
            }
        env:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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