name: Send Slack Notification

on:
  workflow_run:
    workflows: ["Continuous Integration for Comment Service"]
    types:
      - completed

jobs:
  slack_notifier:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send notification on Slack using Webhooks
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "The Continuous Integration for Comment Service workflow has completed successfully at ${{ github.event.workflow_run.completed_at }}."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}