name: SonarQube Scan
on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true
      SONARQUBE_URL:
        required: true

jobs:
  sonarQube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Set up SonarQube scanner
        uses: sonarsource/sonarcloud-github-action@v1.5
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Run SonarQube scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn clean verify sonar:sonar \
          -Dsonar.projectKey=your_project_key \
          -Dsonar.organization=your_organization \
          -Dsonar.host.url=${{ secrets.SONARQUBE_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}