name: SonarQube Scan Comment Service 

on:
  workflow_call:

jobs:
  sonarQube-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: 17

    - name: SonarQube Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      with:
        projectBaseDir: .
        args: >
          -Dsonar.organization=devops-video-sharing
          -Dsonar.projectKey=DevOps-Video-Sharing_CommentService
      

    # - name: Cache SonarQube packages
    #   uses: actions/cache@v3
    #   with:
    #     path: ~/.sonar/cache
    #     key: ${{ runner.os }}-sonar-cache
    #     restore-keys: ${{ runner.os }}-sonar-cache

    # - name: Build and analyze with SonarQube
    #   env:
    #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #   run: |
    #     mvn clean install
    #     mvn sonar:sonar -Dsonar.projectKey=DevOps-Video-Sharing_VideoSharingFrontend -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN
